#!/usr/bin/env bash
# Regenerates the committed example artifacts and the README section that shows
# them. Runs identically locally and in CI.
#
#   ./scripts/generate-example.sh
#
# Produces:
#   examples/complete/manifest.json      extracted manifest (the readable artifact)
#   examples/complete/terraform.tfstate  the real state file the manifest lives in
#   docs/.header.md                      example section injected between markers
#   README.md                            regenerated by terraform-docs, if installed
#
# The example deliberately uses only the random/null/local providers and public
# module sources, so the state file contains no credentials and is safe to commit.
# Keep it that way: do not add a module or provider that needs secrets.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
EXAMPLE_DIR="$REPO_ROOT/examples/complete"
HEADER="$REPO_ROOT/docs/.header.md"
MANIFEST="$EXAMPLE_DIR/manifest.json"

TOFU="${TOFU:-tofu}"

echo "==> Applying $EXAMPLE_DIR"
cd "$EXAMPLE_DIR"
# Wipe only the resolution cache, so providers and modules are resolved fresh every
# run exactly as CI does (the lock file is not committed). State is deliberately
# KEPT: reusing it holds resource ids stable, so regenerating produces a diff only
# when something genuinely changed rather than on every run.
rm -rf .terraform .terraform.lock.hcl terraform.tfstate.backup
"$TOFU" init -no-color -input=false >/dev/null
"$TOFU" apply -no-color -input=false -auto-approve >/dev/null

echo "==> Extracting manifest"
jq '.resources[]
    | select(.module=="module.version_manifest" and .type=="terraform_data")
    | .instances[0].attributes.input.value
    | fromjson' terraform.tfstate > "$MANIFEST"

# Terraform writes state with a trailing newline; keep the manifest tidy too.
python3 -c "
import json,sys
p='$MANIFEST'
json.dump(json.load(open(p)), open(p,'w'), indent=2, sort_keys=True)
open(p,'a').write('\n')
"

# Keeping the committed artifacts stable needs care on two counts:
#
#   * OpenTofu bumps `serial` on every apply even when nothing changed, and the
#     `check_results` block is emitted in a non-deterministic order, so a freshly
#     applied state always differs from the committed one.
#   * root_config.git_commit records this repo's own HEAD, so it changes on every
#     commit to the branch -- which would drag the whole state file along with it.
#
# So: if the manifest is unchanged apart from git_commit, nothing of substance
# happened and both artifacts are restored. Rather than doctor the state file --
# which would defeat the point of committing a real one -- the committed pair is
# simply left as the genuine output of the last run that changed something.
if git -C "$REPO_ROOT" rev-parse --git-dir >/dev/null 2>&1 &&
   git -C "$REPO_ROOT" ls-files --error-unmatch "$MANIFEST" >/dev/null 2>&1; then
  committed="$(git -C "$REPO_ROOT" show "HEAD:examples/complete/manifest.json" 2>/dev/null || echo '{}')"
  strip='del(.root_config.git_commit)'
  if [ "$(printf '%s' "$committed" | jq -S "$strip")" = "$(jq -S "$strip" "$MANIFEST")" ]; then
    echo "    no substantive change; restoring committed manifest and state"
    git -C "$REPO_ROOT" checkout -- \
      "examples/complete/manifest.json" \
      "examples/complete/terraform.tfstate"
  else
    echo "    manifest changed; keeping newly applied manifest and state"
  fi
fi

echo "==> Rendering README section"
python3 - "$REPO_ROOT" <<'PY'
import json, pathlib, sys

root = pathlib.Path(sys.argv[1])
manifest = json.loads((root / "examples/complete/manifest.json").read_text())
config = (root / "examples/complete/main.tf").read_text().rstrip()
header_path = root / "docs/.header.md"

BEGIN, END = "<!-- BEGIN_EXAMPLE -->", "<!-- END_EXAMPLE -->"

def short(v, n=12):
    return v if v in ("n/a", "unknown") else v[:n] + "…"

rows = []
for key in sorted(manifest["modules"]):
    m = manifest["modules"][key]
    rows.append(
        f'| `{key}` | `{m["source_type"]}` | `{m["declared_ref"]}` | `{m["ref_type"]}` '
        f'| `{m["resolved_version"]}` | `{short(m["resolved_commit"])}` | `{short(m["content_hash"])}` |'
    )

prov = []
for addr in sorted(manifest["providers"]):
    p = manifest["providers"][addr]
    name = addr.rsplit("/", 1)[-1]
    prov.append(
        f'| `{name}` | `{p["constraints"]}` | `{p["version"]}` | `{p["installed_binary_version"]}` |'
    )

# An abridged excerpt: one representative entry per source shape.
picks = ["registry_range_pin", "git_tag_bare", "git_branch_main", "local_path"]
excerpt = {
    "schema": manifest["schema"],
    "root_config": manifest["root_config"],
    "providers": manifest["providers"],
    "modules": {k: manifest["modules"][k] for k in picks if k in manifest["modules"]},
}

body = f"""{BEGIN}
<!-- Generated by scripts/generate-example.sh -- do not edit by hand. -->

### Example configuration

Every module source shape this module can encounter, in one configuration. It uses
only public, credential-free sources, so `tofu apply` needs no secrets and creates
no cloud infrastructure. Live at [`examples/complete`](examples/complete).

```hcl
{config}
```

### What gets recorded

Applying the above produces this, keyed by module. Commit SHAs and content hashes
are truncated here for width; the committed artifact has them in full.

| Module | `source_type` | `declared_ref` | `ref_type` | `resolved_version` | `resolved_commit` | `content_hash` |
| --- | --- | --- | --- | --- | --- | --- |
{chr(10).join(rows)}

Note what the three registry entries show: `registry_range_pin` was declared as
`~> 0.25` and `registry_unpinned` declared no version at all, yet both record the
exact version that ran. And `git_default_branch` — which names no ref whatsoever —
resolves to the same commit as `git_branch_main`, because that is the repository's
default branch.

Providers are recorded with both the version the lock file selected and the version
whose binary was actually on disk:

| Provider | `constraints` | `version` | `installed_binary_version` |
| --- | --- | --- | --- |
{chr(10).join(prov)}

### Manifest shape

Abridged to four representative modules. The full artifact is committed at
[`examples/complete/manifest.json`](examples/complete/manifest.json), and the state
file it was extracted from is at
[`examples/complete/terraform.tfstate`](examples/complete/terraform.tfstate).

```json
{json.dumps(excerpt, indent=2, sort_keys=True)}
```
{END}"""

text = header_path.read_text()
if BEGIN in text and END in text:
    pre = text.split(BEGIN)[0]
    post = text.split(END, 1)[1]
    header_path.write_text(pre + body + post)
else:
    raise SystemExit(f"markers {BEGIN} / {END} not found in {header_path}")
print(f"    injected {len(rows)} module rows, {len(prov)} provider rows")
PY

if command -v terraform-docs >/dev/null 2>&1; then
  echo "==> Regenerating README.md"
  cd "$REPO_ROOT"
  terraform-docs markdown . --config .terraform-docs.yml \
    --output-file README.md --output-mode inject >/dev/null
else
  echo "==> terraform-docs not installed; skipping README regeneration"
fi

echo "==> Done"
